FROM nginx:alpine



# Copy nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Create directories for Let's Encrypt
RUN mkdir -p /var/www/certbot

# Expose ports
EXPOSE 80 443

# Start nginx
CMD ["nginx", "-g", "daemon off;"]