FROM node:22-alpine AS base

# Install pnpm in base image
RUN corepack enable pnpm

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# copy pnpm specific files
COPY package.json /app/package.json
COPY pnpm-lock.yaml /app/pnpm-lock.yaml
COPY pnpm-workspace.yaml /app/pnpm-workspace.yaml
COPY turbo.json /app/turbo.json

# copy project related files
COPY packages/common-logic /app/packages/common-logic
COPY packages/common-models /app/packages/common-models
COPY packages/components-library /app/packages/components-library
COPY packages/eslint-config /app/packages/eslint-config
COPY packages/icons /app/packages/icons
COPY packages/text-editor /app/packages/text-editor
COPY packages/typescript-config /app/packages/typescript-config
COPY packages/ui /app/packages/ui
COPY packages/utils /app/packages/utils
COPY apps/web /app/apps/web

# Install dependencies based on the preferred package manager
RUN pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app

COPY --from=deps /app/ ./

ARG BUILD_MODE=production
ARG NEXT_PUBLIC_APP_DOMAIN
ARG NEXT_PUBLIC_SERVER_DOMAIN

ENV NEXT_PUBLIC_APP_DOMAIN=$NEXT_PUBLIC_APP_DOMAIN
ENV NEXT_PUBLIC_SERVER_DOMAIN=$NEXT_PUBLIC_SERVER_DOMAIN

# turn on standalone only for Docker build
ARG NEXT_FOR_DOCKER=1
ENV NEXT_FOR_DOCKER=${NEXT_FOR_DOCKER}

# Build web app using Turbo
RUN pnpm turbo build --filter=@apps/web

# Production image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/next.config.mjs ./apps/web/next.config.mjs

USER nextjs

ARG PORT=3000
ENV PORT=${PORT}

EXPOSE ${PORT}

CMD ["node", "apps/web/server.js"]