export { default as QuestionModel } from "./Question";
export { default as QuizModel } from "./Quiz";
export { default as QuizAttemptModel } from "./QuizAttempt";
export { default as AssignmentModel } from "./Assignment";
export { default as AssignmentSubmissionModel } from "./AssignmentSubmission";
export type { IQuestion } from "./Question";
export type { IQuiz } from "./Quiz";
export type { IQuizAttempt } from "./QuizAttempt";
export type { IAssignment } from "./Assignment";
export type { IAssignmentSubmission } from "./AssignmentSubmission";
